<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="1" time="0.042"><testcase classname="test_calpyt" file="test_calpyt.py" line="5" name="test_answer" time="0.0040209293365478516"><failure message="assert 4 == 5
 +  where 4 = func(3)">def test_answer():
&gt;       assert func(3) == 5
E       assert 4 == 5
E        +  where 4 = func(3)

test_calpyt.py:7: AssertionError</failure></testcase></testsuite>